"""add is_active to students

Revision ID: 091fd7821f19
Revises: cded6c18abdb
Create Date: 2026-06-23 17:46:03.952307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091fd7821f19'
down_revision: Union[str, Sequence[str], None] = 'cded6c18abdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_enrollment_year'), table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_enrollment_year'), 'students', ['enrollment_year'], unique=False)
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
