"""initial schema

Revision ID: cded6c18abdb
Revises: 
Create Date: 2026-06-23 16:33:39.579520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cded6c18abdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'max_seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index(op.f('idx_enrollment_year'), 'students', ['enrollment_year'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('idx_grade'), 'enrollments', ['grade'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('idx_enrollment_unique'), 'enrollments', ['student_id', 'course_id'], unique=False)
    except Exception:
        pass
    op.add_column('courses', sa.Column('max_seats', mysql.INTEGER(), server_default=sa.text("'60'"), autoincrement=False, nullable=True))
    try:
        op.create_index(op.f('idx_course_code'), 'courses', ['course_code'], unique=False)
    except Exception:
        pass
    op.create_table('department_transfer_log',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transfer_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
